spring.application.name=securitydemo

spring.security.user.name=Nishant
spring.security.user.password=Spidy@2004

#spring.h2.console.enabled=true
#spring.h2.console.settings.web-allow-others=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.generate-unique-name=false

spring.app.jwtExpiration=300000000
spring.app.jwtSecret=mySecreteKey22072004876598327456hsjdfkjshdvkjshvcjhsbcjsbc

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.example.securitydemo=DEBUG

#PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/securityapp
#spring.datasource.username=postgres
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#MySql
spring.datasource.url=jdbc:mysql://localhost:3306/springsecurity
spring.datasource.username=root
spring.datasource.password=Spidy@2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
