spring.application.name=securitydemo

spring.security.user.name=Nishant
spring.security.user.password=Spidy@2004

spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

spring.datasource.url=jdbc:h2:mem:test
spring.datasource.generate-unique-name=false

spring.app.jwtExpiration=300000000
spring.app.jwtSecret=mySecreteKey@22072004
